name = "your-config-worker"

# 主入口点 - 处理来自App的配置请求
[[workers]]
name = "main-api"
entry_point = "src/index.js"
route = "try-65y.pages.dev/*"

# **新增：后台管理系统入口点**
[[workers]]
name = "admin-dashboard"
entry_point = "src/admin.js"
route = "admin.try-65y.pages.dev/*"  # 使用单独的子域名

# KV命名空间绑定（两个Worker可共享）
[[kv_namespaces]]
binding = "TOKEN_KV"
id = "your-kv-namespace-id"
