name = "try" # 请修改为您的 Worker 名称
compatibility_date = "2024-10-05"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ""

# D1 数据库绑定配置
[[d1_databases]]
binding = "DB" # 在代码中访问数据库的变量名
database_name = "tvbox-customer-device-db" # 您的数据库名称
database_id = "94c551ee-25e6-4302-8a98-e7f562bbcfe1" # 替换为您的真实 Database ID
