name = "tvbox-worker"
compatibility_date = "2024-10-05"
compatibility_flags = [ "nodejs_compat" ]

# 添加这一行 - 指定入口文件
main = "_worker.js"

[[d1_databases]]
binding = "DB"
database_name = "tvbox-customer-device-db"
database_id = "94c551ee-25e6-4302-8a98-e7f562bbcfe1"
