name = "tvbox-config-worker"
compatibility_date = "2024-01-18"

# KV 命名空间配置（需要先在Cloudflare Dashboard创建）
kv_namespaces = [
  { binding = "CODES", id = "7ba5a96533964d46b94dde8fa1b375d1" },
  { binding = "DEVICES", id = "f918d0ab4f494261b3915afef705eda9" },
  { binding = "SESSIONS", id = "477e537c10dc49d3af387945a5c9ada2" }
]

# 环境变量配置
[vars]
WORKER_DOMAIN = "try15d.pages.dev"
ENVIRONMENT = "production"
CODE_LENGTH = "12"
CODE_EXPIRE = "300"
DEVICE_EXPIRE_DAYS = "30"
SESSION_EXPIRE = "3600"
ADMIN_USERNAME = "xujing"
ADMIN_PASSWORD = "Ardis-417062."
JSON_CONFIG_URL = "https://devilardis.github.io/15DAYsTry/NIUBI.json"

# 部署配置
[env.production]
name = "tvbox-config-worker-production"

# 预览环境配置（可选）
[env.preview]
name = "tvbox-config-worker-preview"
vars = [
  { ENVIRONMENT = "preview" },
  { WORKER_DOMAIN = "preview-domain.pages.dev" }
]
