name: Deploy Worker and Database

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install Wrangler
        run: npm install -g wrangler
        
      - name: Configure Wrangler
        run: |
          echo "CLOUDFLARE_API_TOKEN configured via secrets"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      - name: Apply Complete Database Migration
        run: |
          # 使用重试机制应对网络问题
          for i in {1..3}; do
            if wrangler d1 execute tvbox-customer-device-db --file=migrations/0001_complete_schema.sql --remote; then
              echo "Migration completed successfully"
              break
            else
              echo "Attempt $i failed, retrying in 5 seconds..."
              sleep 5
            fi
          done
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      - name: Deploy Worker
        run: |
          wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
