name: Deploy Worker and Database

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    # 关键修复：指定使用支持 Node.js 20 的更高版本运行器
    strategy:
      matrix:
        node-version: [20.x] # 明确指定 Node.js 20 版本

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install Wrangler
        run: npm install -g wrangler
        
      - name: Configure Wrangler
        run: |
          wrangler config --api-key ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Debug - List D1 Databases
        run: |
          wrangler d1 list
          
      - name: Apply Database Migrations
        run: |
          wrangler d1 execute token-device-db --file=migrations/0001_create_tables.sql --remote
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      - name: Deploy Worker
        run: |
          wrangler deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
