name: Deploy Worker and Database

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          # 移除 cache: 'npm' 这一行！
          
      - name: Install Wrangler
        run: npm install -g wrangler
        
      - name: Configure Wrangler
        run: |
          wrangler config --api-key ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Apply Database Migrations
        run: |
          wrangler d1 execute token-device-db --file=migrations/0001_create_tables.sql --remote
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      - name: Deploy Worker
        run: |
          wrangler deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
