name: Deploy Worker and Database

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'  # 现在可以保留缓存了
          
      - name: Configure Wrangler
        run: |
          wrangler config --api-key ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Apply Database Migrations
        run: |
          wrangler d1 execute token-device-db --file=migrations/0001_create_tables.sql --remote
          
      - name: Deploy Worker
        run: |
          wrangler deploy
